services:
  database:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=teste"
    ports: 
      - 5441:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
volumes:
  pgdata: